{{- if (or .Values.nodeExporter.enabled .Values.tags.nodeExporter) }}
{{- if (or .Values.hardenedNodeExporter.enabled .Values.tags.hardenedNodeExporter) }}
{{- required "Cannot set both nodeExporter and hardenedNodeExporter to true" "" }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-node-exporter
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-node-exporter
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Values.nodeExporter.jobLabel }}
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: {{ $.Release.Name }}
  endpoints:
  - port: metrics
    {{- if .Values.nodeExporter.serviceMonitor.interval }}
    interval: {{ .Values.nodeExporter.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.nodeExporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.nodeExporter.serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- if .Values.nodeExporter.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.nodeExporter.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.nodeExporter.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.nodeExporter.serviceMonitor.relabelings | indent 4 }}
{{- end }}
{{- end }}
